logging:
  level:
    root: WARN

ibm.mq.jms:
  queueManager: queueManagerName
  queueName: queueName
  hostName: hostOrIp
  port: 1414
  channel: channelName
  userName: userName
  password: password

rabbitmq:
  hostname: localhost
  port: 5672
  queueName: queueName
